### ISSUE TITLE
Twitch Error

### ISSUE THREAD

**Issue by LaKo13** [FLWL/autovod#1]

**Comment by FLWL** [comment]
The Twitch API has changed since I last updated this repository. I have a fixed version of the program locally. I'll clean it up and commit if there is interest.

**Comment by LaKo13** [comment]
I meant to delete it as I managed to fix it. Here should be the way it's suppose to set up with the new API. 

autovod.py  row 99-105

```
print("Fetching latest broadcasts from Twitch...")
# twitch_api_link = "https://api.twitch.tv/kraken/channels/" + twitch_channel_name + "/videos?client_id=" + twitch_client_id + "&broadcast_type=archive"
twitch_api_link = "https://api.twitch.tv/kraken/channels/" + twitch_channel_name + "/videos?broadcast_type=archive" 
headers = {'Client-ID': 'YOUR CLIENT ID', 'Accept': 'application/vnd.twitchtv.v5+json'}
twitch_response_text = requests.get(twitch_api_link, headers=headers).text
twitch_response = json.loads(twitch_response_text)
print("Twitch response (max 128 chars): " + twitch_response_text[:128] + (" ..." if len(twitch_response_text) > 128 else ""))
```

In general I was really interested towards the results in general and whether monitoring the chat would be a better option. Perhaps even a combination of both? If you have any input or learnings to share I would greatly appreciate that!

**Comment by FLWL** [comment]
Certainly it would. I have not checked how to retrieve chat logs or how difficult it is. Many different methods and their combinations could be thought of.

For example a few years back I pulled a video frame every 0.25 seconds and checked a certain coordinate for yellow pixels that would indicate a PUBG endgame screen. Or red pixels for kills. Wasn't 100% reliable but worked fair enough. You can look up Igneous Highlights channel on YouTube where I used this program on a small streamer who agreed to cooperate. If some videos are laggy then it is just the way the stream was and not the fault of this program.

In general don't expect amazing results from the simple loudest volume detection logic. It's just something that is fast and captures something at least remotely meaningful. Works better for some games and some type of streams than others. If someone comes up with some other good general way to detect highlights then I am not against adding it to this repo.
